// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdzqe0Zf90F1FGsrWQ0Q-rVCQarx1ygjs',
    appId: '1:339495634069:web:a8f6d862c8cc5dce5fc79c',
    messagingSenderId: '339495634069',
    projectId: 'chatapp01-4aa79',
    authDomain: 'chatapp01-4aa79.firebaseapp.com',
    storageBucket: 'chatapp01-4aa79.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgoSec96P9uwTrC25p8yZAPMQWiemvaDY',
    appId: '1:339495634069:android:c39146bc00f860d15fc79c',
    messagingSenderId: '339495634069',
    projectId: 'chatapp01-4aa79',
    storageBucket: 'chatapp01-4aa79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrRRdFYjnDRdlQj80qHbz0vgwcgrvY-4Y',
    appId: '1:339495634069:ios:79d254226552970d5fc79c',
    messagingSenderId: '339495634069',
    projectId: 'chatapp01-4aa79',
    storageBucket: 'chatapp01-4aa79.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrRRdFYjnDRdlQj80qHbz0vgwcgrvY-4Y',
    appId: '1:339495634069:ios:bef010d5db728b055fc79c',
    messagingSenderId: '339495634069',
    projectId: 'chatapp01-4aa79',
    storageBucket: 'chatapp01-4aa79.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
